name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 0'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: jarvuh/pvescriptskothub

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "."
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"

      # --- НОВЫЕ ШАГИ ДЛЯ СКАЧИВАНИЯ ФАЙЛОМ ---
      
      - name: Pull and Save Image to File
        run: |
          FULL_IMAGE_NAME="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          # Скачиваем только что собранный образ
          docker pull $FULL_IMAGE_NAME
          # Сохраняем в tar-архив
          docker save -o image.tar $FULL_IMAGE_NAME
          # Максимально сжимаем архив с помощью gzip для медленного интернета
          gzip -9 image.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pvescriptskothub-tar # Название архива, который вы будете скачивать
          path: image.tar.gz
          retention-days: 3 # Файл удалится через 3 дня, чтобы не занимать место
