name: Build and Publish Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 0' # Запуск каждое воскресенье в 00:00

env:
  IMAGE_NAME: JarVuh/pvescriptskothub

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Авторизация на Docker Hub с использованием секретов репозитория
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Сборка образа и его отправка на Docker Hub (Используем стабильный v6)
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "."
          file: "./Dockerfile"
          push: true
          tags: "${{ env.IMAGE_NAME }}:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
